import './globals.css';

import type { Metadata } from 'next';

import { ColorThemeProvider } from '@/components/providers/ColorThemeProvider';
import { NavBar } from '@/components/ui/NavBar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light-500 text-dark-500 transition-colors dark:bg-dark-500 dark:text-light-500">
        <ColorThemeProvider>
          <NavBar />
          {children}
        </ColorThemeProvider>
      </body>
    </html>
  );
}
