import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ColorThemeProvider } from '@/components/providers/ColorThemeProvider';
import { NavBar } from '@/components/ui/NavBar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-light-500 text-dark-500 transition-colors dark:bg-dark-500 dark:text-light-500 ${montserrat.className}`}
      >
        <ColorThemeProvider>
          <NavBar />
          {children}
        </ColorThemeProvider>
      </body>
    </html>
  );
}
