import './globals.css';

import type { Metadata } from 'next';

import { ColorThemeProvider } from '@/components/providers/ColorThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light text-dark dark:bg-dark dark:text-light">
        <ColorThemeProvider>{children}</ColorThemeProvider>
      </body>
    </html>
  );
}
