name: Create Unlighthouse Audit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-unlighthouse-audit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: Insights
      url: https://insights.car-service.842u.dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Unlighthouse CLI
        run: npm install --global @unlighthouse/cli

      - name: Bump Lighthouse Version
        run: |
          cd $(npm prefix -g)
          ls -a
          cd $(npm prefix -g)/node_modules/@unlighthouse/cli
          cd ./node_modules/@unlighthouse/core
          sed -i /"lighthouse": "^9.6.8"/"lighthouse": "^11.5.0"/ package.json
          cd $(npm prefix -g)/node_modules/@unlighthouse/cli
          npm install
          cd ./node_modules/@unlighthouse/core/dist
          sed -i /lighthouse-core/core/ index.mjs

      - name: Install Puppeteer
        run: npm install --global puppeteer

      - name: Run Unlighthouse Audit
        run: npx unlighthouse-ci --site https://www.car-service.842u.dev --build-static --throttle --no-cache --samples 3

      - name: Push To Static Audit Repo
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:842u/insights-car-service.git
          BRANCH: main
          FOLDER: .unlighthouse
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 842u_BOT
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/23544888?v=4
        uses: Ilshidur/action-discord@master
        with:
          args: |
            New AUDIT for {{ EVENT_PAYLOAD.repository.full_name }}
            https://insights.car-service.842u.dev
