name: Create Unlighthouse Audit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-unlighthouse-audit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: Insights
      url: https://insights.car-service.842u.dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Npm Global Directory
        id: npm-global-dir
        run: echo "dir=$(npm prefix -g)" >> ${GITHUB_OUTPUT}

      - name: Cache Npm Global Dependencies
        uses: actions/cache@v4
        id: npm-global-cache
        env:
          cache-name: cache-npm-global-dependencies
        with:
          path: ${{ steps.npm-global-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}

      - name: Install Unlighthouse CLI
        if: steps.npm-global-cache.outputs.cache-hit != 'true'
        run: npm install --global @unlighthouse/cli

      - name: Run Unlighthouse Audit
        run: unlighthouse-ci --site https://www.car-service.842u.dev --build-static --throttle --no-cache

      - name: Push To Static Audit Repo
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:842u/insights-car-service.git
          BRANCH: main
          FOLDER: .unlighthouse
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 842u_BOT
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/23544888?v=4
        uses: Ilshidur/action-discord@master
        with:
          args: |
            New AUDIT for {{ EVENT_PAYLOAD.repository.full_name }}
            https://insights.car-service.842u.dev
