name: Vercel Deploy Production

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  vercel-deploy-production:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://car-service.842u.dev
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_VERSION: ${{ steps.vercel-version.outputs.vercel_version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Npm Global Directory
        id: npm-global-dir
        run: echo "dir=$(npm prefix -g)" >> ${GITHUB_OUTPUT}

      - name: Cache Npm Global Dependencies
        uses: actions/cache@v4
        id: npm-global-cache
        env:
          cache-name: cache-npm-global-dependencies
        with:
          path: |
            ${{ steps.npm-global-dir.outputs.dir }}
          key: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ env.VERCEL_VERSION }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ env.VERCEL_VERSION }}

      - name: Install Vercel CLI
        if: steps.npm-global-cache.outputs.cache-hit != 'true'
        run: npm install --global vercel@latest

      - name: Get Vercel CLI Version
        id: vercel-version
        run: echo "version=$(vercel --version)" >> ${GITHUB_OUTPUT}

      - name: Pull Vercel Remote Environment Variables
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 842u_BOT
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/23544888?v=4
        uses: Ilshidur/action-discord@master
        with:
          args: |
            New PRODUCTION for {{ EVENT_PAYLOAD.repository.full_name }}
            https://car-service.842u.dev

  create-unlighthouse-audit:
    needs: vercel-deploy-production
    uses: ./.github/workflows/create-unlighthouse-audit.yaml
    secrets: inherit
